name: climbing_gym_app
description: A Flutter app for managing climbing gym routes and user interactions.
publish_to: 'none'
version: 0.8.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_3d_controller: ^2.2.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/models/
    - assets/logo/